### ISSUE TITLE
Resnet18 backbone 

### ISSUE THREAD

**Issue by ARGSK** [xuannianz/keras-CenterNet#10]
In resnet.py how can I use the resnet18 backbone ? if I change the backbone to resnet18/resnet34 it didn't detect any object.
Is resnet18 faster than resnet50?

**Comment by xuannianz** [comment]
Hi @ARGSK , Have you trained with there two backbones?
Must be faster.

**Comment by ARGSK** [comment]
Thank you, but is there a pretrained model for resnet18/resnet34?

**Comment by xuannianz** [comment]
https://github.com/qubvel/classification_models/releases

**Comment by ARGSK** [comment]
thank you
