### ISSUE TITLE
Convert pytorch pre-trained model to keras

### ISSUE THREAD

**Issue by WangyiNTU** [xuannianz/keras-CenterNet#11]
Thanks for your code. Is there any idea to load the pre-trained model of Pytorch CentetNet to this Keras? So, we can use the original pre-trained model for fine-tuning. Thanks. @xuannianz

**Comment by xuannianz** [comment]
Yes, I will release the script to convert hourglass weights later.
For resnet and dla, I have not found any projects that implemented DCNv2 in tf.
