### ISSUE TITLE
 No module named 'utils.compute_overlap'

### ISSUE THREAD

**Issue by apardogi** [xuannianz/keras-CenterNet#13]
Hello,

I've been trying to train a model following the example available in the Readme but when executing the train.py file I'm getting this error:

```
Traceback (most recent call last):
  File "train.py", line 356, in <module>
    main()
  File "train.py", line 334, in main
    args,
  File "train.py", line 90, in create_callbacks
    from eval.pascal import Evaluate
  File "/home/keras-CenterNet/eval/pascal.py", line 18, in <module>
    from .common import evaluate
  File "/home/keras-CenterNet/eval/common.py", line 21, in <module>
    from utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'utils.compute_overlap'
```

I've used keras-retinanet before and I was able to easily run the inference code in this repository.

**Comment by ARGSK** [comment]
Same with me when I use validation path with csv

**Comment by xuannianz** [comment]
Do you have the 'compute_overlap' module?
If yes, how about replacing https://github.com/xuannianz/keras-CenterNet/blob/39cb123a94d7774490df28e637240de03577f912/eval/pascal.py#L18 with `from eval.common import evaluate` and make sure the module is right there.
If not, try to build by python setup.py build_ext --inplace as in keras-retinanet.

**Comment by ARGSK** [comment]
compute_overlap is .pyx not py, how I can import it or convert it?

**Comment by lyy-fighting** [comment]
> compute_overlap is .pyx not py, how I can import it or convert it?

Look at my questions Thanks!, (https://github.com/xuannianz/keras-CenterNet/issues/14)  'batch_dims' error

**Comment by lyy-fighting** [comment]
> Do you have the 'compute_overlap' module?
> If yes, how about replacing
> 
> https://github.com/xuannianz/keras-CenterNet/blob/39cb123a94d7774490df28e637240de03577f912/eval/pascal.py#L18
> 
> with `from eval.common import evaluate` and make sure the module is right there.
> If not, try to build by python setup.py build_ext --inplace as in keras-retinanet.

Could you look at my questions? [https://github.com/xuannianz/keras-CenterNet/issues/14](url) Thanks! 'batch_dims' error

**Comment by lyy-fighting** [comment]
In first row, add  code
import sys
sys.path.append("..")
