### ISSUE TITLE
voc  resnet50 	mAP=0.7290 

### ISSUE THREAD

**Issue by zgsxwsdxg** [xuannianz/keras-CenterNet#15]
您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？

centernet 不是free anchor的吗？为什么还要用nms？

**Comment by zgsxwsdxg** [comment]
还想问一下，您的实现推理时运行时间多少了？谢谢

**Comment by zcunyi** [comment]
> 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？
> 
> centernet 不是free anchor的吗？为什么还要用nms？

你训练成功了吗

**Comment by zgsxwsdxg** [comment]
> 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？
> centernet 不是free anchor的吗？为什么还要用nms？
> 
> 你训练成功了吗

没有呢，我是想先了解下性能如何？好的话开始训练

**Comment by zcunyi** [comment]
Pytorch 的训练成功了，keras
这个还么有，但是目前在研究tf版本的

发自我的 iPhone

**Comment by zgsxwsdxg** [comment]
> Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone
> […](#)
> 在 2019年12月20日，上午11:28，zgsxwsdxg ***@***.***> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



> Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone
> […](#)
> 在 2019年12月20日，上午11:28，zgsxwsdxg ***@***.***> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，朋友。你说pytorch训练成功时官方那个么？

**Comment by zcunyi** [comment]
是的，tf版本的也训练成功了

发自我的 iPhone

**Comment by zgsxwsdxg** [comment]
> 是的，tf版本的也训练成功了 发自我的 iPhone
> […](#)
> 在 2019年12月24日，上午11:09，zgsxwsdxg ***@***.***> 写道： Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone … 在 2019年12月20日，上午11:28，zgsxwsdxg @.***> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone … 在 2019年12月20日，上午11:28，zgsxwsdxg @.***> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 您好，朋友。你说pytorch训练成功时官方那个么？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

tf版的效果怎么样？准确率和运行时间

**Comment by zcunyi** [comment]
还可以

发自我的 iPhone

**Comment by zgsxwsdxg** [comment]
> 还可以 发自我的 iPhone
> […](#)
> 在 2019年12月24日，上午11:38，zgsxwsdxg ***@***.***> 写道： 是的，tf版本的也训练成功了 发自我的 iPhone … 在 2019年12月24日，上午11:09，zgsxwsdxg @.> 写道： Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone … 在 2019年12月20日，上午11:28，zgsxwsdxg @.> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone … 在 2019年12月20日，上午11:28，zgsxwsdxg @.***> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 您好，朋友。你说pytorch训练成功时官方那个么？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. tf版的效果怎么样？准确率和运行时间 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

朋友，能发个链接么？tf版的centernet

**Comment by Aries5522** [comment]
> 还可以 发自我的 iPhone
> […](#)
> 在 2019年12月24日，上午11:38，zgsxwsdxg ***@***.***> 写道： 是的，tf版本的也训练成功了 发自我的 iPhone … 在 2019年12月24日，上午11:09，zgsxwsdxg @.> 写道： Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone … 在 2019年12月20日，上午11:28，zgsxwsdxg @.> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone … 在 2019年12月20日，上午11:28，zgsxwsdxg @.***> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 您好，朋友。你说pytorch训练成功时官方那个么？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. tf版的效果怎么样？准确率和运行时间 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



> 还可以 发自我的 iPhone
> […](#)
> 在 2019年12月24日，上午11:38，zgsxwsdxg ***@***.***> 写道： 是的，tf版本的也训练成功了 发自我的 iPhone … 在 2019年12月24日，上午11:09，zgsxwsdxg @.> 写道： Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone … 在 2019年12月20日，上午11:28，zgsxwsdxg @.> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Pytorch 的训练成功了，keras 这个还么有，但是目前在研究tf版本的 发自我的 iPhone … 在 2019年12月20日，上午11:28，zgsxwsdxg @.***> 写道： 您好！感谢您的巨大工作，mAP=0.729 是用了nms的吗？那没有用nms时mAP是多少？ centernet 不是free anchor的吗？为什么还要用nms？ 你训练成功了吗 没有呢，我是想先了解下性能如何？好的话开始训练 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 您好，朋友。你说pytorch训练成功时官方那个么？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. tf版的效果怎么样？准确率和运行时间 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

tf用的哪个链接，能分享下吗，谢谢了
