### ISSUE TITLE
No module named 'keras_resnet'

### ISSUE THREAD

**Issue by ARGSK** [xuannianz/keras-CenterNet#2]
I faced this issue when running inference.py
![Capture](https://user-images.githubusercontent.com/57886896/69045013-0ac5b780-0a07-11ea-9808-48fe2448f5c4.PNG)

**Comment by xuannianz** [comment]
You need to install the packages listed in requirements.txt in advance.

**Comment by ARGSK** [comment]
> You need to install the packages listed in requirements.txt in advance.

Thank you it works, but should I download VOC2007 dataset? or I can test on my own imges

**Comment by xuannianz** [comment]
Of course, you can test on any images in which there are objects of the 20 PASCAL VOC classes.
