### ISSUE TITLE
ValueError: Shape must be rank 4 but is rank 3 for 'lambda_1/concat' (op: 'ConcatV2') with input shapes: 

### ISSUE THREAD

**Issue by chenxiao521** [xuannianz/keras-CenterNet#24]
你好，代码运行到 detections = tf.concat([topk_x1, topk_y1, topk_x2, topk_y2, scores, class_ids], axis=-1)。出现了下列的错误，ValueError: Shape must be rank 4 but is rank 3 for 'lambda_1/concat' (op: 'ConcatV2') with input shapes: [?,?,100,?], [?,?,100,?], [?,?,100,?], [?,?,100,?], [?,100,1], [?,100,1], [].

**Comment by chenxiao521** [comment]
tensorflow版本导致

**Comment by sxp0100** [comment]
请教下你的版本是多少的，我也遇到这个问题，tensorflow升级到2.1仍然报错
