### ISSUE TITLE
Do you have the issue like first img inference slow on your tf or keras tf backend?

### ISSUE THREAD

**Issue by AutumnZ-94** [xuannianz/keras-CenterNet#31]
Maybe this is not a literate "issue" about this repo.

Just noticed that you are using TF 1.15.  The first image fed in to model during inference is always slow on my TF 1.14, while pytorch performs normally.  Do you have a similiar condition？

BTW, [https://github.com/fizyr/keras-retinanet/issues/747#issue-372118785](url) this issue said set`TF_CUDNN_USE_AUTOTUNE=0` on TF1.11 works, but not works on my 1.14.

Any experience on you about this?

**Comment by huynhtnhut97** [comment]
In case u wanna test FPS on your model then just feed the image twice then the second time will illustrate the correct FPS of your contemporary model.
